version: '3.8'
services: 
    react-client:
      container_name: client
      build:
        context: .
        dockerfile: Dockerfile
      volumes:
        - './:/usr/app'
        - '/usr/app/node_modules'
      ports:
        - 3000:3000
      environment:
        - CHOKIDAR_USEPOLLING=true